name: SSH into AWS Instance

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: SSH into AWS Instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@65.0.133.226 "echo 'Server action performed'"
